site_name: 王明超AI笔记
site_url: https://mingchao.wang/biji_ai/
site_description: 王明超AI笔记
site_author: mingchao.wang

repo_url: https://github.com/wmc1992/biji_ai
edit_uri: ""

theme:
    # name: mkdocs
    # name: readthedocs
    # name: ivory
    # name: rtd-dropdown
    # name: gitbook
    # name: bootstrap
    # name: 'rtd-dropdown'
    # name: material
    name: null
    custom_dir: 'cinder'
    locale: en
    analytics: {gtag: 'G-274394082'}
    highlightjs: true
    hljs_languages:
        - yaml
        - django
        - python

nav:
    - "Home": "index.md"
    - "算法":
        - "常用距离": "常用距离.md"
        - "Jacobi矩阵": "Jacobi矩阵/Jacobi矩阵.md"
        - "sklearn计算不平衡数据的权重": "sklearn计算不平衡数据的权重.md"
        - "Batch_Norm": "batch_normalize.md"
        - "Layer_Norm": "layer_normalize.md"
        - "KL散度": "KL散度.md"
        - "线性回归": "线性回归.md"
        - "正则化": "正则化/正则化.md"
        - "特征值与特征向量": "线性代数/特征值与特征向量.md"
        - "微分方程": "微分方程.md"

extra_css:
    - css/extra.css

markdown_extensions:
    - toc:
        permalink: False
    - mdx_gh_links:
        user: mkdocs
        repo: mkdocs
    - admonition
    - attr_list
    - def_list
    - pymdownx.arithmatex

extra_javascript:
  # other extra java script
  - mathjax-config.js
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML


copyright: Copyright &copy; 2021 Microsoft Research

plugins:
    - search
    # - redirects:
    #     redirect_maps:
    #         user-guide/plugins.md: dev-guide/plugins.md
    #         user-guide/custom-themes.md: dev-guide/themes.md
    #         user-guide/styling-your-docs.md: user-guide/choosing-your-theme.md
